motor_enable_node:
  ros__parameters:
    pwm_a: 13
    a_in1: 6
    a_in2: 26
    pwm_b: 12
    b_in3: 20
    b_in4: 16
    chip_path: "/dev/gpiochip0"
    motor_mode: "pwm"
    MIN_PWM: 0

imu_estimator_node:
  ros__parameters:
    alpha: 0.85

imu_node:
  ros__parameters:
    SAMPLE_FREQ_MIRCOSEC: 2000

pid_controller_node:
  ros__parameters:
    kp: 30.0
    ki: 0.0
    kd: 2.0
    setpoint: 0.0
    fall_detection_threshold: 0.78
    max_velocity_cmd: 6.0

motor_encoder_node:
  ros__parameters:
    motor_a_encoder_a: 17
    motor_a_encoder_b: 27
    motor_b_encoder_a: 22
    motor_b_encoder_b: 23
    chip_path: "/dev/gpiochip0"
    event_time_threshold: 100000

velocity_controller_node:
  ros__parameters:
    omega_no_load: 31.4
    kp_vel: 0.30
    ki_vel: 0.05
    kd_vel: 0.006
    max_slew_rate: 50.0

diag_logger_node:
  ros__parameters:
    log_rate_hz: 100.0
    csv_path: "/home/mmcgraw/balance_log.csv"